# **Primeiros passos em análises de dados e visualizações gráficas com Python**

# **Dia 2 - Dataframe**

# Bibliotecas

É a forma de organizar e estruturar coleções de módulos com diferentes funções

Existe duas alternativas para importar essas ferramentas para usar no seu código

`import <módulo>`

`from <biblioteca> import <módulo>`

In [3]:
# biblioteca math
import math

# função para somar dados
sum([1,1,3,4])

9

In [4]:
# criar uma variável do tipo date (data)
from datetime import date
hoje = date(2026, 1, 8)
print(hoje)

2026-01-08

In [5]:
type(hoje)

datetime.date

## **Instalação de bibliotecas**

Python possui várias bibliotecas integradas, mas é possível instalar novas bibliotecas usando a função `pip install`

`pip install <nova_biblioteca>`

In [6]:
# pip install pandas

In [7]:
# para importar bibliotecas, é possível dar "apelidos" usando import + as
import pandas as pd

# **Biblioteca Pandas**

A biblioteca **Pandas** tem código aberto que fornece estruturas de dados de alta performance e fácil de utilizar, é também uma ótima ferramenta para manipulação de dados.

O nome Pandas vem da combinação de *Panel Data e Python Data Analysis*.

O apelido usado pela comunidade para o **Pandas** é o **pd**, portanto, carregar o **Pandas** e nomear como pd é considerado uma prática padrão para toda a documentação do **Pandas**.

Ela possui uma ótima documentação:
https://pandas.pydata.org/


<img style="float: center;" src="https://img-c.udemycdn.com/course/480x270/2760528_6a2f.jpg"  width="300"/>

In [8]:
# importando pandas
import pandas as pd

# **Pandas Dataframe**

É a principal estrutura semelhante à planilhas de Excel/ Google Sheet.
- É uma estrutura de dados **tabular bidimensional** mutável em tamanho
- Pode armazenar diferentes tipos de dados (int, float, string, date e etc.),
- Possui eixos rotulados (linhas e colunas)

<img style="float: center;" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Frwegener2.github.io%2Fsarp_lessons%2F_images%2Fpandas_dataframe.png&f=1&nofb=1&ipt=0c349e8c8c8b9d9b997930dbcccece110f7ef88e5bc885e7b3842d0a4bd19e08&ipo=images" width="500"/>

In [9]:
# criando um dataframe a partir de uma lista
lista = ["André", "Enzo", "Lia"]

dataframe = pd.DataFrame(lista)
dataframe

       0
0  André
1   Enzo
2    Lia

In [10]:
# nomeando a coluna
dataframe = pd.DataFrame(lista, columns=['Nomes'])
dataframe

   Nomes
0  André
1   Enzo
2    Lia

## **Series**

*Series* é uma matriz rotulada unidimensional capaz de conter qualquer tipo de dados (inteiros, strings, decimais, etc.)

Cada coluna no *dataframe* é uma series, é igual uma coluna no Excel/ Google Sheet.

O índice começa no zero (como em strings e listas).

<img style="float: center;" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fdatascientyst.com%2Fcontent%2Fimages%2F2021%2F12%2Fpandas-series-index-values.png&f=1&nofb=1&ipt=a45ececfad8d981be231a04f055a1998c6b5c9915e03b77739f53f52cf01db50&ipo=images" width="500"/>

In [11]:
# transformando nossa lista anterior em uma series
nomes = pd.Series(lista)
print(nomes)

0    André
1     Enzo
2      Lia
dtype: object

In [12]:
# criando uma serie com índice texto
alunos = pd.Series(lista, index=["a", "b", "c"],  name = "nomes")
alunos

a    André
b     Enzo
c      Lia
Name: nomes, dtype: object

# **Importando dados para o Colab**

Vamos começar a olha nossos dados dos pinguins da Antartica que trabalharemos até o fim do curso.

Para isso, precisamos importar a planilha para nossa sessão de trabalho no Google Colab.

Primeiro, vamos fazer o Colab "enxergar" nosso Google Drive

In [13]:
# importamos módulo que faz a conexão entre Google Colab e Drive
from google.colab import drive

# solicitar autorização para acessar a sua conta do Google Drive
drive.mount('/content/drive')

Mounted at /content/drive

In [14]:
# lendo uma planilha em csv
# # preencha as aspas com o local da pasta e adiciona o nome do arquivo que a planilha está
# por exemplo pd.read_csv("/content/drive/mydrive/pinguim_palmer.csv", index = 0)
pinguim = pd.read_csv("", index_col=0)

In [15]:
# imprimindo planilha
print(pinguim)

               Nome_comum                Especie       Ilha  \
ID
P1      Pinguim-de-adélia     Pygoscelis adeliae  Torgersen
P2      Pinguim-de-adélia     Pygoscelis adeliae  Torgersen
P3      Pinguim-de-adélia     Pygoscelis adeliae  Torgersen
P4      Pinguim-de-adélia     Pygoscelis adeliae  Torgersen
P5      Pinguim-de-adélia     Pygoscelis adeliae  Torgersen
...                   ...                    ...        ...
P340  Pinguim-de-barbicha  Pygoscelis antarctica      Dream
P341  Pinguim-de-barbicha  Pygoscelis antarctica      Dream
P342  Pinguim-de-barbicha  Pygoscelis antarctica      Dream
P343  Pinguim-de-barbicha  Pygoscelis antarctica      Dream
P344  Pinguim-de-barbicha  Pygoscelis antarctica      Dream

            Estagio_Reprodutivo    Data_ovo  Comprimento_bico  \
ID
P1    Adulto,  Estágio de Ovo 1  11/11/2007              39.1
P2    Adulto,  Estágio de Ovo 1  11/11/2007              39.5
P3    Adulto,  Estágio de Ovo 1  11/16/2007              40.3
P4    Adulto,  Estágio de Ovo 1  11/16/2007               NaN
P5    Adulto,  Estágio de Ovo 1  11/16/2007              36.7
...                         ...         ...               ...
P340  Adulto,  Estágio de Ovo 1  11/19/2009              55.8
P341  Adulto,  Estágio de Ovo 1  11/21/2009              43.5
P342  Adulto,  Estágio de Ovo 1  11/21/2009              49.6
P343  Adulto,  Estágio de Ovo 1  11/21/2009              50.8
P344  Adulto,  Estágio de Ovo 1  11/21/2009              50.2

      Profundidade_bico  Comprimento_asa  Massa_corporal   Sexo
ID
P1                 18.7            181.0          3750.0  Macho
P2                 17.4            186.0          3800.0  Fêmea
P3                 18.0            195.0          3250.0  Fêmea
P4                  NaN              NaN             NaN    NaN
P5                 19.3            193.0          3450.0  Fêmea
...                 ...              ...             ...    ...
P340               19.8            207.0          4000.0  Macho
P341               18.1            202.0          3400.0  Fêmea
P342               18.2            193.0          3775.0  Macho
P343                NaN            210.0          4100.0  MACHO
P344               18.7            198.0          3775.0  FEMEA

[344 rows x 10 columns]

In [16]:
# visualizando a planilha
pinguim

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo
ID,,,,,,,,,,
P1,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.1,18.7,181.0,3750.0,Macho
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.5,17.4,186.0,3800.0,Fêmea
P3,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,40.3,18.0,195.0,3250.0,Fêmea
P4,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,NaN,NaN,NaN,NaN,NaN
P5,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,36.7,19.3,193.0,3450.0,Fêmea
...,...,...,...,...,...,...,...,...,...,...
P340,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/19/2009,55.8,19.8,207.0,4000.0,Macho
P341,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,43.5,18.1,202.0,3400.0,Fêmea
P342,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,49.6,18.2,193.0,3775.0,Macho
P343,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,50.8,NaN,210.0,4100.0,MACHO
P344,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,50.2,18.7,198.0,3775.0,FEMEA

# **Resumo dos dados**

Vamos visualizar algumas informações dos nossos dados.

In [17]:
# retorna por padrao as 5 primeiras linhas
pinguim.head()

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo
ID,,,,,,,,,,
P1,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.1,18.7,181.0,3750.0,Macho
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.5,17.4,186.0,3800.0,Fêmea
P3,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,40.3,18.0,195.0,3250.0,Fêmea
P4,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,NaN,NaN,NaN,NaN,NaN
P5,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,36.7,19.3,193.0,3450.0,Fêmea

In [18]:
# retorna por padrao as 5 últimas linhas
pinguim.tail()

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo
ID,,,,,,,,,,
P340,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/19/2009,55.8,19.8,207.0,4000.0,Macho
P341,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,43.5,18.1,202.0,3400.0,Fêmea
P342,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,49.6,18.2,193.0,3775.0,Macho
P343,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,50.8,NaN,210.0,4100.0,MACHO
P344,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,50.2,18.7,198.0,3775.0,FEMEA

In [19]:
# quantas linhas e quantas colunas tem o dataframe?
pinguim.shape

(344, 10)

In [20]:
# verificando os nomes das colunas
pinguim.columns

Index(['Nome_comum', 'Especie', 'Ilha', 'Estagio_Reprodutivo', 'Data_ovo',
       'Comprimento_bico', 'Profundidade_bico', 'Comprimento_asa',
       'Massa_corporal', 'Sexo'],
      dtype='object')

In [21]:
# algumas informacoes dos dados
pinguim.info()

<class 'pandas.core.frame.DataFrame'>
Index: 344 entries, P1 to P344
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Nome_comum           344 non-null    object
 1   Especie              344 non-null    object
 2   Ilha                 344 non-null    object
 3   Estagio_Reprodutivo  344 non-null    object
 4   Data_ovo             344 non-null    object
 5   Comprimento_bico     340 non-null    float64
 6   Profundidade_bico    339 non-null    float64
 7   Comprimento_asa      342 non-null    float64
 8   Massa_corporal       338 non-null    float64
 9   Sexo                 333 non-null    object
dtypes: float64(4), object(6)
memory usage: 29.6+ KB

## Pinguins de Palmer

Dados coletados pela Dra. Kristen Gorman e pela "Palmer Station, Antarctica LTER", membros da "Long Term Ecological Research Network".

- Três espécies de pinguins

<img src="https://allisonhorst.github.io/palmerpenguins/reference/figures/lter_penguins.png" width="500"/>


- Dados de 344 pinguins coletados nas três ilhas no Arquipélago de Palmer na Antártica

- Dados de espécie, ilha, comprimento do bico, profundidade do bico, comprimento da asa, massa corporal, sexo e ano
<img src="https://allisonhorst.github.io/palmerpenguins/reference/figures/culmen_depth.png" width="500"/>

Mais informações acesse:

[Sobre o conjunto de dados](https://pypi.org/project/palmerpenguins/)

[Sobre as variáveis do conjunto de dados](https://allisonhorst.github.io/palmerpenguins/reference/penguins_raw.html)

# **Seleção e filtragem de dados**

## **Seleção por nome de coluna**

Selecionar colunas por rótulo (nome da coluna) utilizando .loc

`<nome dataframe>.loc["nome da coluna"]`

<img style="background-color: white;" src="https://pandas.pydata.org/docs/_images/03_subset_columns.svg"/>

In [22]:
# selecionar uma coluna por nome (ou seja, uma series) - uma dimensão
pinguim.loc[:,"Data_ovo"]

ID
P1      11/11/2007
P2      11/11/2007
P3      11/16/2007
P4      11/16/2007
P5      11/16/2007
           ...
P340    11/19/2009
P341    11/21/2009
P342    11/21/2009
P343    11/21/2009
P344    11/21/2009
Name: Data_ovo, Length: 344, dtype: object

In [23]:
# selecionar múltiplas colunas por nome - duas dimensões
pinguim.loc[:,["Especie", "Sexo", "Data_ovo"]]

                    Especie   Sexo    Data_ovo
ID
P1       Pygoscelis adeliae  Macho  11/11/2007
P2       Pygoscelis adeliae  Fêmea  11/11/2007
P3       Pygoscelis adeliae  Fêmea  11/16/2007
P4       Pygoscelis adeliae    NaN  11/16/2007
P5       Pygoscelis adeliae  Fêmea  11/16/2007
...                     ...    ...         ...
P340  Pygoscelis antarctica  Macho  11/19/2009
P341  Pygoscelis antarctica  Fêmea  11/21/2009
P342  Pygoscelis antarctica  Macho  11/21/2009
P343  Pygoscelis antarctica  MACHO  11/21/2009
P344  Pygoscelis antarctica  FEMEA  11/21/2009

[344 rows x 3 columns]

In [24]:
# selecionar um intervalo de colunas
pinguim.loc[:, "Comprimento_bico":"Comprimento_asa"]

      Comprimento_bico  Profundidade_bico  Comprimento_asa
ID
P1                39.1               18.7            181.0
P2                39.5               17.4            186.0
P3                40.3               18.0            195.0
P4                 NaN                NaN              NaN
P5                36.7               19.3            193.0
...                ...                ...              ...
P340              55.8               19.8            207.0
P341              43.5               18.1            202.0
P342              49.6               18.2            193.0
P343              50.8                NaN            210.0
P344              50.2               18.7            198.0

[344 rows x 3 columns]

## **Seleção de linhas por nome da linha**

Selecionar linhas por nome da linha utilizando .loc

`<nome dataframe>.iloc[nome da linha,]`

<img style="background-color: white;" src="https://pandas.pydata.org/docs/_images/03_subset_rows.svg"/>

In [25]:
pinguim.head()

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo
ID,,,,,,,,,,
P1,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.1,18.7,181.0,3750.0,Macho
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.5,17.4,186.0,3800.0,Fêmea
P3,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,40.3,18.0,195.0,3250.0,Fêmea
P4,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,NaN,NaN,NaN,NaN,NaN
P5,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,36.7,19.3,193.0,3450.0,Fêmea

In [26]:
# .loc - selecionar uma linha utilizando nome da linha como Series
# uma dimensão
pinguim.loc["P1", :]

Nome_comum                     Pinguim-de-adélia
Especie                       Pygoscelis adeliae
Ilha                                   Torgersen
Estagio_Reprodutivo    Adulto,  Estágio de Ovo 1
Data_ovo                              11/11/2007
Comprimento_bico                            39.1
Profundidade_bico                           18.7
Comprimento_asa                            181.0
Massa_corporal                            3750.0
Sexo                                       Macho
Name: P1, dtype: object

In [27]:
# .loc - selecionar uma linha utilizando nome da linha como Dataframe
# duas dimensões
pinguim.loc[["P1"], :]

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo
ID,,,,,,,,,,
P1,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.1,18.7,181.0,3750.0,Macho

In [28]:
# .loc - selecionar múltiplas linhas com índices
pinguim.loc["P2":, :]

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo
ID,,,,,,,,,,
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.5,17.4,186.0,3800.0,Fêmea
P3,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,40.3,18.0,195.0,3250.0,Fêmea
P4,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,NaN,NaN,NaN,NaN,NaN
P5,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,36.7,19.3,193.0,3450.0,Fêmea
P6,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,39.3,20.6,190.0,3650.0,Macho
...,...,...,...,...,...,...,...,...,...,...
P340,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/19/2009,55.8,19.8,207.0,4000.0,Macho
P341,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,43.5,18.1,202.0,3400.0,Fêmea
P342,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,49.6,18.2,193.0,3775.0,Macho
P343,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,50.8,NaN,210.0,4100.0,MACHO
P344,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,50.2,18.7,198.0,3775.0,FEMEA

## **Selecionar linhas e colunas**

Selecionar colunas e linhas por índice e nome de colunas utilizando .loc

`<nome dataframe>.iloc[índice, "nome de coluna"]`

<img style="background-color: white;" src="https://pandas.pydata.org/docs/_images/03_subset_columns_rows.svg"/>

In [29]:
# selecionar valor único
pinguim.loc["P1","Especie"]

'Pygoscelis adeliae'

In [30]:
# selecionar linhas e colunas
pinguim.loc["P1":"P10","Especie":"Data_ovo"]

                Especie       Ilha        Estagio_Reprodutivo    Data_ovo
ID
P1   Pygoscelis adeliae  Torgersen  Adulto,  Estágio de Ovo 1  11/11/2007
P2   Pygoscelis adeliae  Torgersen  Adulto,  Estágio de Ovo 1  11/11/2007
P3   Pygoscelis adeliae  Torgersen  Adulto,  Estágio de Ovo 1  11/16/2007
P4   Pygoscelis adeliae  Torgersen  Adulto,  Estágio de Ovo 1  11/16/2007
P5   Pygoscelis adeliae  Torgersen  Adulto,  Estágio de Ovo 1  11/16/2007
P6   Pygoscelis adeliae  Torgersen  Adulto,  Estágio de Ovo 1  11/16/2007
P7   Pygoscelis adeliae  Torgersen  Adulto,  Estágio de Ovo 1  11/15/2007
P8   Pygoscelis adeliae  Torgersen  Adulto,  Estágio de Ovo 1  11/15/2007
P9   Pygoscelis adeliae  Torgersen  Adulto,  Estágio de Ovo 1   11/9/2007
P10  Pygoscelis adeliae  Torgersen  Adulto,  Estágio de Ovo 1   11/9/2007

In [31]:
# selecionar linhas e algumas colunas
pinguim.loc["P1":"P10",["Especie", "Ilha", "Sexo"]]

                Especie       Ilha   Sexo
ID
P1   Pygoscelis adeliae  Torgersen  Macho
P2   Pygoscelis adeliae  Torgersen  Fêmea
P3   Pygoscelis adeliae  Torgersen  Fêmea
P4   Pygoscelis adeliae  Torgersen    NaN
P5   Pygoscelis adeliae  Torgersen  Fêmea
P6   Pygoscelis adeliae  Torgersen  Macho
P7   Pygoscelis adeliae  Torgersen  Fêmea
P8   Pygoscelis adeliae  Torgersen  Macho
P9   Pygoscelis adeliae  Torgersen    NaN
P10  Pygoscelis adeliae  Torgersen    NaN

## Seleção po índice

Da mesma forma como em *strings* e lista, é possível selecionar por índice utilizando .iloc

`<dataframe>.iloc[<número índice>]`

In [32]:
pinguim.head()

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo
ID,,,,,,,,,,
P1,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.1,18.7,181.0,3750.0,Macho
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.5,17.4,186.0,3800.0,Fêmea
P3,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,40.3,18.0,195.0,3250.0,Fêmea
P4,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,NaN,NaN,NaN,NaN,NaN
P5,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,36.7,19.3,193.0,3450.0,Fêmea

In [33]:
# selecionar uma linha passando um índice (número inteiro)
pinguim.iloc[1]

Nome_comum                     Pinguim-de-adélia
Especie                       Pygoscelis adeliae
Ilha                                   Torgersen
Estagio_Reprodutivo    Adulto,  Estágio de Ovo 1
Data_ovo                              11/11/2007
Comprimento_bico                            39.5
Profundidade_bico                           17.4
Comprimento_asa                            186.0
Massa_corporal                            3800.0
Sexo                                       Fêmea
Name: P2, dtype: object

In [34]:
# selecionar por posição de linha e posição de coluna com .iloc
pinguim.iloc[2, 0]

'Pinguim-de-adélia'

In [35]:
# selecionar por posição de uma coluna com .iloc - Series
# uma dimensão
pinguim.iloc[:,0]

ID
P1        Pinguim-de-adélia
P2        Pinguim-de-adélia
P3        Pinguim-de-adélia
P4        Pinguim-de-adélia
P5        Pinguim-de-adélia
               ...
P340    Pinguim-de-barbicha
P341    Pinguim-de-barbicha
P342    Pinguim-de-barbicha
P343    Pinguim-de-barbicha
P344    Pinguim-de-barbicha
Name: Nome_comum, Length: 344, dtype: object

In [36]:
# selecionar por posição de múltiplas colunas com .iloc
# duas dimensões
pinguim.iloc[:,1:3]

                    Especie       Ilha
ID
P1       Pygoscelis adeliae  Torgersen
P2       Pygoscelis adeliae  Torgersen
P3       Pygoscelis adeliae  Torgersen
P4       Pygoscelis adeliae  Torgersen
P5       Pygoscelis adeliae  Torgersen
...                     ...        ...
P340  Pygoscelis antarctica      Dream
P341  Pygoscelis antarctica      Dream
P342  Pygoscelis antarctica      Dream
P343  Pygoscelis antarctica      Dream
P344  Pygoscelis antarctica      Dream

[344 rows x 2 columns]

# **Filtrar dados**

## **Filtro com operadores lógicos**

- Igual a: ==
- Diferente de: !=
- Maior que: >
- Menor que: <
- Maior ou igual que: =>
- Menor ou igual que: <=

In [37]:
# usar operadores de comparações para filtrar informações específicas
pinguim["Sexo"] == "Fêmea"

ID
P1      False
P2       True
P3       True
P4      False
P5       True
        ...
P340    False
P341     True
P342    False
P343    False
P344    False
Name: Sexo, Length: 344, dtype: bool

In [38]:
# associar filtro a variável
filtro_femea = pinguim['Sexo'] == "Fêmea"

In [39]:
# selecionar os dados no dataframe usando o filtro
pinguim[filtro_femea]

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo
ID,,,,,,,,,,
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.5,17.4,186.0,3800.0,Fêmea
P3,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,40.3,18.0,195.0,3250.0,Fêmea
P5,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,36.7,19.3,193.0,3450.0,Fêmea
P7,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/15/2007,38.9,17.8,181.0,NaN,Fêmea
P13,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/15/2007,41.1,17.6,182.0,3200.0,Fêmea
...,...,...,...,...,...,...,...,...,...,...
P333,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,45.2,16.6,191.0,3250.0,Fêmea
P336,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,45.6,19.4,194.0,3525.0,Fêmea
P338,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/27/2009,46.8,16.5,189.0,3650.0,Fêmea
P339,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/19/2009,45.7,17.0,195.0,3650.0,Fêmea
P341,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,43.5,18.1,202.0,3400.0,Fêmea

In [40]:
# ou declare o filtro diretamente na seleção
pinguim[pinguim['Sexo'] == "Fêmea"]

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo
ID,,,,,,,,,,
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.5,17.4,186.0,3800.0,Fêmea
P3,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,40.3,18.0,195.0,3250.0,Fêmea
P5,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,36.7,19.3,193.0,3450.0,Fêmea
P7,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/15/2007,38.9,17.8,181.0,NaN,Fêmea
P13,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/15/2007,41.1,17.6,182.0,3200.0,Fêmea
...,...,...,...,...,...,...,...,...,...,...
P333,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,45.2,16.6,191.0,3250.0,Fêmea
P336,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,45.6,19.4,194.0,3525.0,Fêmea
P338,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/27/2009,46.8,16.5,189.0,3650.0,Fêmea
P339,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/19/2009,45.7,17.0,195.0,3650.0,Fêmea
P341,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,43.5,18.1,202.0,3400.0,Fêmea

## **Filtro com múltiplos operadores**

- E: `&`
- Ou: `|`

In [42]:
# criar filtros
femea = pinguim["Sexo"] == "Fêmea"
sp = pinguim["Especie"] == "Pygoscelis adeliae"

In [43]:
# filtro com operadores de comparação e lógicos
pinguim[femea & sp]

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo
ID,,,,,,,,,,
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.5,17.4,186.0,3800.0,Fêmea
P3,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,40.3,18.0,195.0,3250.0,Fêmea
P5,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,36.7,19.3,193.0,3450.0,Fêmea
P7,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/15/2007,38.9,17.8,181.0,NaN,Fêmea
P13,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/15/2007,41.1,17.6,182.0,3200.0,Fêmea
...,...,...,...,...,...,...,...,...,...,...
P143,Pinguim-de-adélia,Pygoscelis adeliae,Dream,"Adulto, Estágio de Ovo 1",11/16/2009,32.1,15.5,188.0,3050.0,Fêmea
P145,Pinguim-de-adélia,Pygoscelis adeliae,Dream,"Adulto, Estágio de Ovo 1",11/16/2009,37.3,16.8,192.0,3000.0,Fêmea
P148,Pinguim-de-adélia,Pygoscelis adeliae,Dream,"Adulto, Estágio de Ovo 1",11/13/2009,36.6,18.4,184.0,3475.0,Fêmea
P149,Pinguim-de-adélia,Pygoscelis adeliae,Dream,"Adulto, Estágio de Ovo 1",11/17/2009,36.0,17.8,195.0,3450.0,Fêmea
P151,Pinguim-de-adélia,Pygoscelis adeliae,Dream,"Adulto, Estágio de Ovo 1",11/17/2009,36.0,17.1,187.0,3700.0,Fêmea

# **Criar colunas e tabelas a partir dos próprios dados**

## **Criar colunas usando operações aritméticas**

In [44]:
# criando coluna com a soma de duas variáveis
pinguim['Massa_corporal_corrigida'] = pinguim['Massa_corporal'] + 100
pinguim.head(2)

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo,Massa_corporal_corrigida
ID,,,,,,,,,,,
P1,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.1,18.7,181.0,3750.0,Macho,3850.0
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.5,17.4,186.0,3800.0,Fêmea,3900.0

In [45]:
# criando coluna com a multiplicação de duas variáveis
pinguim["Peso_kg"] = pinguim["Massa_corporal"] / 1000
pinguim.head(3)

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo,Massa_corporal_corrigida,Peso_kg
ID,,,,,,,,,,,,
P1,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.1,18.7,181.0,3750.0,Macho,3850.0,3.75
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.5,17.4,186.0,3800.0,Fêmea,3900.0,3.80
P3,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,40.3,18.0,195.0,3250.0,Fêmea,3350.0,3.25

## **Criar colunas usando operações com *strings***

In [46]:
# separando uma coluna em várias utilizando a coluna Data_ovo
pinguim.loc[:,["Especie","Data_ovo"]]

                    Especie    Data_ovo
ID
P1       Pygoscelis adeliae  11/11/2007
P2       Pygoscelis adeliae  11/11/2007
P3       Pygoscelis adeliae  11/16/2007
P4       Pygoscelis adeliae  11/16/2007
P5       Pygoscelis adeliae  11/16/2007
...                     ...         ...
P340  Pygoscelis antarctica  11/19/2009
P341  Pygoscelis antarctica  11/21/2009
P342  Pygoscelis antarctica  11/21/2009
P343  Pygoscelis antarctica  11/21/2009
P344  Pygoscelis antarctica  11/21/2009

[344 rows x 2 columns]

In [47]:
# separando Data_ovo em dia, mês e ano
split_data = pinguim["Data_ovo"].str.split("/", n = 2, expand = True)
split_data

       0   1     2
ID
P1    11  11  2007
P2    11  11  2007
P3    11  16  2007
P4    11  16  2007
P5    11  16  2007
...   ..  ..   ...
P340  11  19  2009
P341  11  21  2009
P342  11  21  2009
P343  11  21  2009
P344  11  21  2009

[344 rows x 3 columns]

In [56]:
# criando nova coluna com mês
pinguim["Mês"] = split_data[1]
pinguim["Ano"] = split_data[2]
pinguim.head()

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo,Massa_corporal_corrigida,Peso_kg,Mes,Ano
ID,,,,,,,,,,,,,,
P1,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.1,18.7,181.0,3750.0,Macho,3850.0,3.75,11,2007
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.5,17.4,186.0,3800.0,Fêmea,3900.0,3.80,11,2007
P3,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,40.3,18.0,195.0,3250.0,Fêmea,3350.0,3.25,16,2007
P4,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,2007
P5,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,36.7,19.3,193.0,3450.0,Fêmea,3550.0,3.45,16,2007

# **Excluindo colunas e linhas**

É possível excluir colunas e linhas usando `drop(`.

`<nome do dataframe>.drop(columns = <nome da coluna>, axis = 1)`

In [49]:
# quantas colunas temos?
pinguim.shape

(344, 13)

In [50]:
# excluindo a coluna Data_ovo
pinguim.drop(columns = "Data_ovo").head(2)

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo,Massa_corporal_corrigida,Peso_kg,Mes
ID,,,,,,,,,,,,
P1,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",39.1,18.7,181.0,3750.0,Macho,3850.0,3.75,11
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",39.5,17.4,186.0,3800.0,Fêmea,3900.0,3.80,11

In [51]:
# excluindo colunas
pinguim.drop(columns=['Massa_corporal_corrigida', 'Peso_kg']).head(2)

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo,Mes
ID,,,,,,,,,,,
P1,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.1,18.7,181.0,3750.0,Macho,11
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.5,17.4,186.0,3800.0,Fêmea,11

In [52]:
pinguim.shape

(344, 13)

In [53]:
# excluindo linhas usando índice
# excluindo a primeira linha
pinguim.drop("P1")

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo,Massa_corporal_corrigida,Peso_kg,Mes
ID,,,,,,,,,,,,,
P2,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/11/2007,39.5,17.4,186.0,3800.0,Fêmea,3900.0,3.800,11
P3,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,40.3,18.0,195.0,3250.0,Fêmea,3350.0,3.250,16
P4,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
P5,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,36.7,19.3,193.0,3450.0,Fêmea,3550.0,3.450,16
P6,Pinguim-de-adélia,Pygoscelis adeliae,Torgersen,"Adulto, Estágio de Ovo 1",11/16/2007,39.3,20.6,190.0,3650.0,Macho,3750.0,3.650,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...
P340,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/19/2009,55.8,19.8,207.0,4000.0,Macho,4100.0,4.000,19
P341,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,43.5,18.1,202.0,3400.0,Fêmea,3500.0,3.400,21
P342,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,49.6,18.2,193.0,3775.0,Macho,3875.0,3.775,21
P343,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,50.8,NaN,210.0,4100.0,MACHO,4200.0,4.100,21
P344,Pinguim-de-barbicha,Pygoscelis antarctica,Dream,"Adulto, Estágio de Ovo 1",11/21/2009,50.2,18.7,198.0,3775.0,FEMEA,3875.0,3.775,21

In [54]:
# quantas colunas ficamos?
pinguim.shape

(344, 13)

In [57]:
# também é possível excluir linhas usando filtro
# quais os valores em ano?
pinguim["Ano"].unique()

array(['2007', '2008', '2009'], dtype=object)

In [58]:
# criamos um filtro que exclui ano de 2007
filtro_ano = pinguim["Ano"] != "2007"

In [59]:
# filtramos e adicionamos a novo dataframe
pinguim_ano = pinguim[pinguim["Ano"] != 2007]
pinguim_ano.shape

(344, 14)

# **Correção de dados no dataframe**

É possível também preencher dados vazios ou corrigir palavras com grafias incorretas

In [60]:
# quais os valores da coluna nome comum?
pinguim["Nome_comum"].unique()

array(['Pinguim-de-adélia', 'Pinguim-de-gentoo', 'Pinguim-de-barbicha'],
      dtype=object)

In [61]:
# corrigindo os nomes das espécies com .loc
# exemplo com Pinguim-de-adélia
pinguim.loc[pinguim["Nome_comum"] == "Pinguim-de-adelia", "Nome_comum"] = "Pinguim-de-adélia"

In [62]:
pinguim["Nome_comum"].unique()

array(['Pinguim-de-adélia', 'Pinguim-de-gentoo', 'Pinguim-de-barbicha'],
      dtype=object)

# **Checando valores ausentes**

É possível checar valores ausentes (ou *missing data*) usando a funçao is.na().

O Python representa valores ausentes como `NA`.

`<nome dataframe>.isna()`

In [63]:
# valores ausentes no dataframe
pinguim.isna()

,Nome_comum,Especie,Ilha,Estagio_Reprodutivo,Data_ovo,Comprimento_bico,Profundidade_bico,Comprimento_asa,Massa_corporal,Sexo,Massa_corporal_corrigida,Peso_kg,Mes,Ano
ID,,,,,,,,,,,,,,
P1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
P2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
P3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
P4,False,False,False,False,False,True,True,True,True,True,True,True,False,False
P5,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P340,False,False,False,False,False,False,False,False,False,False,False,False,False,False
P341,False,False,False,False,False,False,False,False,False,False,False,False,False,False
P342,False,False,False,False,False,False,False,False,False,False,False,False,False,False
P343,False,False,False,False,False,False,True,False,False,False,False,False,False,False
P344,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [64]:
# contando número de linhas com valores ausentes numa coluna
pinguim["Sexo"].isna().sum().item()

11

In [65]:
pinguim.shape

(344, 14)

In [66]:
# retirando linha com valores ausentes
pinguim_limpo = pinguim.dropna()

In [67]:
pinguim_limpo.shape

(324, 14)

# **Salvando os resultados finais**

É possível salvar tabelas editadas utilizando a função .to_csv()

```
<nome dataframe>.to_csv("nome do arquivo.csv")
```

In [ ]:
# preencha as aspas com o local da pasta e adiciona o nome do arquivo que gostaria para a planilha
# por exemplo pinguim_limpo.to_csv("/content/drive/mydrive/pinguim_limpo.csv")
pinguim_limpo.to_csv("")